name: krushimitra
description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: 1.2.2
  flutter_staggered_animations: ^1.1.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.4.3
  firebase_database: ^11.1.4
  fl_chart: ^0.69.0
  firebase_auth: ^5.1.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.4
  image: ^3.0.1
  dropdown_search: ^5.0.6
  camera: ^0.11.0+2
  google_generative_ai: ^0.4.6
  geolocator: ^13.0.2
  permission_handler: ^10.0.0
  geocode: ^1.0.3
  free_map: ^1.0.6
  lottie: ^3.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/plants.tflite
    - assets/google_sign_in.png
    - assets/img1.jpeg
    - assets/img2.jpeg
    - assets/img3.jpeg
    - assets/img4.jpeg
    - assets/loading.json

  fonts:
    - family: Sevillana
      fonts:
        - asset: font/Sevillana-Regular.ttf
    - family: SourceSans3
      fonts:
        - asset: font/SourceSans3-VariableFont_wght.ttf
